name: 'Deploy to aws s3'
description: 'Deploy to aws s3'
inputs:
  bucket:
    description: 'The name of the bucket to deploy to'
    required: true
  bucket-region:
    description: 'The region of the bucket to deploy to'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder to deploy'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed site'
    #value: 'https://${{ inputs.bucket }}.s3.${{ inputs.bucket-region }}.amazonaws.com'
runs:
  using: docker
  image: Dockerfile
